FROM amazon/aws-sam-cli-emulation-image-go1.x

# To learn more context around use of `amazonlinux:2` image please read comment in java11/build/Dockerfile
# Copying root from runtimes image to AL2
FROM amazonlinux:2
COPY --from=0 / /rootfs

# Install build tools
# The base image essentially corrupts the RPM DB,
#  so we need to make changes for yum to run successfully.
RUN chmod 1777 /tmp && \
  /usr/bin/python2 -c "from ConfigParser import SafeConfigParser; \
  yum_conf = SafeConfigParser(); \
  yum_conf.read('/etc/yum.conf'); \
  yum_conf.has_section('main') or yum_conf.add_section('main'); \
  yum_conf.set('main', 'plugins', '1'); \
  f = open('/etc/yum.conf', 'w'); \
  yum_conf.write(f); \
  f.close();" && \
  rpm --rebuilddb && \
  yum groupinstall -y development && \
  yum install -d1 -y \
  tar \
  gzip \
  unzip \
  python3 \
  grep \
  curl \
  make \
  rsync \
  gcc-c++ \
  binutils \
  procps \
  libgmp3-dev \
  zlib1g-dev \
  liblzma-dev \
  libxslt-devel \
  libmpc-devel \
  && yum clean all

# Copying root from AL2 to runtimes image
FROM amazon/aws-sam-cli-emulation-image-go1.x
COPY --from=1 /rootfs /

RUN yum install -y jq

# Install Go
RUN yum install -y git && \
  curl -L https://golang.org/dl/go1.16.5.linux-amd64.tar.gz | tar -zx -C /usr/local
ENV PATH=$PATH:/usr/local/go/bin:/root/go/bin
# Set GOPROXY envvar to avoid using the default proxy.golang.org proxy
ENV GOPROXY=direct

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install && rm awscliv2.zip && rm -rf ./aws

# Install SAM CLI in a dedicated Python virtualenv
ARG SAM_CLI_VERSION
RUN curl -L "https://github.com/awslabs/aws-sam-cli/archive/v$SAM_CLI_VERSION.zip" -o "samcli.zip" && \
  unzip samcli.zip && python3 -m venv /usr/local/opt/sam-cli && \
  /usr/local/opt/sam-cli/bin/pip3 --no-cache-dir install -r ./aws-sam-cli-$SAM_CLI_VERSION/requirements/reproducible-linux.txt && \
  /usr/local/opt/sam-cli/bin/pip3 --no-cache-dir install ./aws-sam-cli-$SAM_CLI_VERSION && \
  rm samcli.zip && rm -rf aws-sam-cli-develop

ENV PATH=$PATH:/usr/local/opt/sam-cli/bin

ENV LANG=en_US.UTF-8

# Wheel is required by SAM CLI to build libraries like cryptography. It needs to be installed in the system
# Python for it to be picked up during `sam build`
RUN pip3 install wheel

COPY ATTRIBUTION.txt /
